/**
 * Sync blocks + themes from test-site-master API.
 *
 * Writes:
 *   src/blocks/<Name>.ts           — Payload block configs
 *   src/components/blocks/<Name>Block.tsx — React components
 *   src/registry.ts                — auto-generated index of all blocks + themes
 *
 * Usage: npm run sync
 */
import 'dotenv/config'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const MASTER = process.env.MASTER_URL || 'http://localhost:3001'

async function fetchAll(collection: string) {
  const res = await fetch(`${MASTER}/api/${collection}?limit=500&where[_status][equals]=published`)
  if (!res.ok) throw new Error(`Failed to fetch ${collection}: HTTP ${res.status}`)
  const data = await res.json()
  return data.docs || []
}

function toPascalCase(s: string): string {
  return s.replace(/[-_\s]+(.)/g, (_, c: string) => c.toUpperCase()).replace(/^(.)/, c => c.toUpperCase())
}

async function main() {
  console.log(`→ Syncing from ${MASTER}...\n`)

  // ── Sync blocks ───────────────────────────────────────────
  const blocks = await fetchAll('block-definitions')
  console.log(`Found ${blocks.length} published blocks`)

  const blocksDir = path.join(ROOT, 'src', 'blocks')
  const componentsDir = path.join(ROOT, 'src', 'components', 'blocks')
  fs.mkdirSync(blocksDir, { recursive: true })
  fs.mkdirSync(componentsDir, { recursive: true })

  // Clean previous sync
  for (const f of fs.readdirSync(blocksDir)) fs.unlinkSync(path.join(blocksDir, f))
  for (const f of fs.readdirSync(componentsDir)) fs.unlinkSync(path.join(componentsDir, f))

  const blockEntries: Array<{ slug: string; name: string; category: string; blockType: string; description: string; variantGuide: string }> = []

  for (const block of blocks) {
    const name = block.name || toPascalCase(block.slug)

    if (block.configCode) {
      fs.writeFileSync(path.join(blocksDir, `${name}.ts`), block.configCode, 'utf8')
    }
    if (block.componentCode) {
      fs.writeFileSync(path.join(componentsDir, `${name}Block.tsx`), block.componentCode, 'utf8')
    }

    blockEntries.push({
      slug: block.slug,
      name,
      category: block.category || '',
      blockType: block.blockType || 'layout',
      description: block.description || '',
      variantGuide: block.variantGuide || '',
    })

    console.log(`  ✓ ${block.slug} → ${name}.ts + ${name}Block.tsx`)
  }

  // ── Sync themes ───────────────────────────────────────────
  const themes = await fetchAll('themes')
  console.log(`\nFound ${themes.length} published themes`)

  const themeEntries: Array<{ slug: string; name: string; category: string; tokens: Record<string, string> }> = []

  for (const t of themes) {
    themeEntries.push({
      slug: t.slug,
      name: t.name,
      category: t.category || '',
      tokens: {
        background: t.background,
        foreground: t.foreground,
        card: t.card,
        cardForeground: t.cardForeground,
        popover: t.popover,
        popoverForeground: t.popoverForeground,
        primary: t.primary,
        primaryForeground: t.primaryForeground,
        secondary: t.secondary,
        secondaryForeground: t.secondaryForeground,
        accent: t.accent,
        accentForeground: t.accentForeground,
        muted: t.muted,
        mutedForeground: t.mutedForeground,
        destructive: t.destructive,
        border: t.border,
        input: t.input,
        ring: t.ring,
      },
    })
    console.log(`  ✓ ${t.slug} (${t.name})`)
  }

  // ── Generate registry ─────────────────────────────────────
  const registryLines = [
    '/* AUTO-GENERATED by npm run sync — do not edit */',
    '',
    '// Block component imports',
    ...blockEntries.map(b => `import { ${b.name}Block } from './components/blocks/${b.name}Block'`),
    '',
    'export const blockComponents: Record<string, React.ComponentType<any>> = {',
    ...blockEntries.map(b => `  '${b.slug}': ${b.name}Block,`),
    '}',
    '',
    `export const blockMeta = ${JSON.stringify(blockEntries, null, 2)} as const`,
    '',
    `export const themeMeta = ${JSON.stringify(themeEntries, null, 2)} as const`,
    '',
    'import React from "react"',
  ]

  fs.writeFileSync(path.join(ROOT, 'src', 'registry.ts'), registryLines.join('\n'), 'utf8')
  console.log(`\n✓ Generated src/registry.ts (${blockEntries.length} blocks, ${themeEntries.length} themes)`)

  console.log('\n✅ Sync complete. Run "npm run dev" to preview.')
}

main().catch(err => {
  console.error('❌', err.message || err)
  process.exit(1)
})
